using System;
using NUnit.Framework;
using Moq;
using System.Collections.Generic;

[TestFixture]
class Class1Test
{
    private Class1 _class1;
    [SetUp]
    public void SetUp()
    {
        _class1 = new Class1();
    }

    [Test]
    public void kj()
    {
        _class1.kj();
        Assert.Fail("autogenerated");
    }
}